"""added cart items

Revision ID: 57325dfdc122
Revises: 11bbf717fba6
Create Date: 2025-02-26 15:25:02.560983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57325dfdc122'
down_revision = '11bbf717fba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('rating')
        batch_op.drop_column('out_of_stock')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('out_of_stock', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('rating', sa.FLOAT(), nullable=False))

    op.drop_table('cart_items')
    # ### end Alembic commands ###
