"""Add is_admin column to User model

Revision ID: 618977ff0d53
Revises: 57325dfdc122
Create Date: 2025-03-02 21:22:50.830590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618977ff0d53'
down_revision = '57325dfdc122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
