"""Add out of stock and ratings column

Revision ID: fa6b6787b25a
Revises: cc8fbdaa7290
Create Date: 2025-02-25 13:09:51.999664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6b6787b25a'
down_revision = 'cc8fbdaa7290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=False, server_default='3.5'))
        batch_op.add_column(sa.Column('out_of_stock', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('out_of_stock')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
